name: Regression Label

on:
  pull_request:
    types: [ labeled ]
jobs:
  re_run:
    # only continue if a push or PR labeled with 'run regression'
    if: github.event.label.name == 'graph-pixi-tests'
    runs-on: ubuntu-latest
    permissions:
      actions: write
    steps:
      - name: Run Cypress tests for graph-pixi
        run: npm run cypress:run -- --spec "cypress/e2e/pixi-interaction/*"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # set repository so we don't have to check out all of the code
          GH_REPO: ${{github.repository}}
