name: Graph Pixi Tests

on:
  push:

jobs:
  re_run:
    runs-on: ubuntu-latest
    permissions:
      actions: write
    steps:
      - name: Run Cypress tests for graph-pixi
        run: npm run cypress:run -- --spec "cypress/e2e/pixi-interaction/*"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # set repository so we don't have to check out all of the code
          GH_REPO: ${{github.repository}}

cypress:
    runs-on: ubuntu-latest
    strategy:
      # when one test fails, DO NOT cancel the other
      # containers, because this will kill Cypress processes
      # leaving the Dashboard hanging ...
      # https://github.com/cypress-io/github-action/issues/48
      fail-fast: false
    steps:
      - uses: browser-actions/setup-chrome@v1
        with:
          chrome-version: stable
      - uses: snow-actions/sparse-checkout@v1.2.0
        with:
          patterns: v3
      - name: Restore Webpack Cache
        id: restore-webpack-cache
        uses: actions/cache/restore@v4
        with:
          path: v3/.cache/webpack/
          key: webpack-dev-build-${{ hashFiles('v3/webpack.config.js') }}
      - uses: cypress-io/github-action@v6
        with:
          working-directory: v3
          start: npm start
          wait-on: 'http://localhost:8080'
          wait-on-timeout: 300
          record: ${{ !!secrets.CYPRESS_RECORD_KEY }}
          browser: chrome
          spec: cypress/e2e/pixi-interaction/**/*.ts
          group: 'Pixi Interaction Tests'
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CODE_COVERAGE: true
          CYPRESS_coverage: true
          SKIP_ESLINT: true
