name: Continuous Integration (CODAP v3)

on:
  push:
    paths:      # only run this workflow if it contains v3 files
      - 'v3/**' # https://docs.github.com/en/actions/using-workflows/triggering-a-workflow#example-including-paths
      - '.github/workflows/v3.yml'
      - '.github/workflows/graph-pixi-tests.yml'

jobs:
  jest:
    name: Run Jest Tests
    runs-on: ubuntu-latest
    steps:
      - uses: snow-actions/sparse-checkout@v1.2.0
        with:
          patterns: v3
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: v3/package-lock.json
      - name: Install Dependencies
        working-directory: v3
        run: npm ci
      - name: Jest Cache
        uses: actions/cache@v4
        with:
          path: /tmp/jest_rt
          key: jest-${{ hashFiles('v3/package-lock.json') }}
      - name: Get number of CPU cores
        id: cpu-cores
        uses: SimenB/github-actions-cpu-cores@v2
      - name: Run Tests
        working-directory: v3
        run: npm run test:coverage -- --maxWorkers=${{ steps.cpu-cores.outputs.count }}
      - name: Archive code coverage results
        uses: actions/upload-artifact@v4
        with:
          name: code-coverage-report
          path: ./
